### ISSUE TITLE
Video tutorial: How to set up Rust to play Screeps Arena

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/screeps#1]
# Tasks

- [x] Create list of steps for setting up Rust to play Screeps Arena
- [ ] Record
- [ ] Create video description for the tutorial
- [ ] Create thumbnail
- [ ] Upload video
- [ ] Tweet

# Video

- [ ] Introduction
  - [ ] What is Screeps Arena
- [ ] Fork and clone repo
- [ ] Setup screeps.toml file
  - [ ] Set destination
- [ ] Run the container `docker run --name screeps_arena -v $(pwd):/code -v /Users/brooks/ScreepsArena:/screepsarena screepsarena:latest`
- [ ] Set up auto running with the command
  - [ ] Install cargo watch
  - [ ] `cargo watch -s "docker start screeps_arena"`
- [ ] Build for Tutorial
  - [ ] Add feature to Cargo.toml
  - [ ] Add feature to screeps.toml
  - [ ] Change import target in main.mjs
  - [ ] Build in docker container
